[target.x86_64-unknown-linux-gnu]
# Build with `docker build -t trsync_build_x86_64-unknown-linux-gnu:latest recipes/linux-x86_64`
image = "trsync_build_x86_64-unknown-linux-gnu:latest"

[target.x86_64-pc-windows-gnu]
# Build with `docker build -t trsync_build_x86_64-unknown-linux-gnu:latest recipes/linux-x86_64`
image = "trsync_build_x86_64-unknown-linux-gnu:latest"

# [target.i686-unknown-linux-gnu]
# # Build with `docker build -t trsync_build_i686-unknown-linux-gnu:latest recipes/linux-i686`
# image = "trsync_build_i686-unknown-linux-gnu:latest"
